In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
import numpy as np

In [6]:
myarr= np.array([[3,4,9], [None,2,7],[8,3,6]])

np.


In [7]:
myarr

array([[3, 4, 9],
       [None, 2, 7],
       [8, 3, 6]], dtype=object)

In [8]:
type(myarr)

numpy.ndarray

In [9]:
myarr.size

9

In [10]:
myarr.ndim

2

In [11]:
myarr.shape

(3, 3)

In [12]:
myarr.dtype

dtype('O')

In [13]:
print("Array stores elements of type: ", myarr.dtype)

Array stores elements of type:  object


In [16]:
myarr[0:1,2]

array([9], dtype=object)

In [17]:
myarr[2:]

array([[8, 3, 6]], dtype=object)

In [18]:
myarr[-1:]

array([[8, 3, 6]], dtype=object)

In [19]:
myarr[-2:]

array([[None, 2, 7],
       [8, 3, 6]], dtype=object)

In [20]:
myarr

array([[3, 4, 9],
       [None, 2, 7],
       [8, 3, 6]], dtype=object)

In [21]:
myarr[0:2,1]

array([4, 2], dtype=object)

myarr[0:2,1:3]

In [24]:
myarr[0:2]

array([[3, 4, 9],
       [None, 2, 7]], dtype=object)

In [25]:
myarr[1:2]

array([[None, 2, 7]], dtype=object)

In [27]:
#Task: Find the mean of every row have them in an array. use numpy

In [1]:
np.mean(myarr, axis=1)

NameError: name 'np' is not defined

NameError: name 'b' is not defined