In [1]:
import numpy as np

In [2]:
arr = [[14, 17, 12, 33, 44],   
       [15, 6, 27, 8, 19],  
       [23, 2, 54, 1, 4, ]]

In [3]:
np.mean(arr)

18.6

In [4]:
np.mean(arr, axis=0)

array([17.33333333,  8.33333333, 31.        , 14.        , 22.33333333])

In [5]:
np.mean(arr, axis=1)

array([24. , 15. , 16.8])

In [8]:
np.median(arr)

15.0

In [9]:
np.median(arr,axis=1)

array([17., 15.,  4.])